version: '3'

services:
  furea2server:
    build: ./furea2server
    command: bash -c 'python manage.py migrate && python /server/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/furea2server
    expose:
      - 8000
    depends_on:
      - postgres
  postgres:
    restart: always
    # 公式からイメージをpull
    image: postgres:latest
    # データベースの永続化
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
  nginx:
    build: ./nginx
    # http://localhost:1337/
    ports:
      - 1337:80
    depends_on:
      - furea2server

volumes:
    postgres_data: