version: '3'

volumes:
  furea2server.db.volume:
    name: furea2server.db.volume

services:
  nginx:
    image: nginx:1.13
    container_name: furea2server.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - web
